<?php

use Faker\Guesser\Name;

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Anggota_model extends CI_Model
{

    public $table = 'anggota';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
        require_once './vendor/fzaninotto/faker/src/autoload.php';
        $this->faker = Faker\Factory::create('id_ID');
    }

    public function getDummyDataAnggota($jumlah = null)
    {
        // $this->faker->addProvider(new Faker\Provider\id_ID\Company($this->faker));
        // echo $this->faker->randomElement($array = array('1', '0'));
        // echo "<br>";
        // die;
        if ($jumlah == null) {
            $data = array(
                'user_id' => $this->faker->realText($this->faker->numberBetween(10, 20)),
                'nama' => $this->faker->name,
                'nik' => $this->faker->nik(),
                'tempat_lahir' => $this->faker->city,
                'tgl_lahir' => $this->faker->date($format = 'Y-m-d', $max = '-20 years'),
                'jenis_kelamin' => $this->faker->randomElement($array = array('Laki-Laki', 'Perempuan')),
                'pekerjaan' => $this->faker->jobTitle(),
                'alamat' => $this->faker->address,
                'no_hp' => $this->faker->phoneNumber,
                'status' => $this->faker->randomElement($array = array('1', '0')),
            );

            $this->Anggota_model->insert($data);
            $this->session->set_flashdata('message', '<div class="alert alert-success" role="alert">Data berhasil ditambahkan.</div>');
            redirect(site_url('anggota'));
        }
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,user_id,nama,nik,tempat_lahir,tgl_lahir,jenis_kelamin,pekerjaan,alamat,no_hp,status');
        $this->datatables->from('anggota');
        //add this line for join
        //$this->datatables->join('table2', 'anggota.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('anggota/read/$1'), 'Read') . " | " . anchor(site_url('anggota/update/$1'), 'Update') . " | " . anchor(site_url('anggota/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('user_id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('nik', $q);
        $this->db->or_like('tempat_lahir', $q);
        $this->db->or_like('tgl_lahir', $q);
        $this->db->or_like('jenis_kelamin', $q);
        $this->db->or_like('pekerjaan', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_hp', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('user_id', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('nik', $q);
        $this->db->or_like('tempat_lahir', $q);
        $this->db->or_like('tgl_lahir', $q);
        $this->db->or_like('jenis_kelamin', $q);
        $this->db->or_like('pekerjaan', $q);
        $this->db->or_like('alamat', $q);
        $this->db->or_like('no_hp', $q);
        $this->db->or_like('status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Anggota_model.php */
/* Location: ./application/models/Anggota_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-26 04:35:23 */
/* http://harviacode.com */