<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pembayaran_model extends CI_Model
{

    public $table = 'pembayaran';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,id_pinjaman,angsuran,cicilan,tgl_jatuh_tempo,tgl_bayar,jumlah,id_user,waktu_insert');
        $this->datatables->from('pembayaran');
        //add this line for join
        //$this->datatables->join('table2', 'pembayaran.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pembayaran/read/$1'), 'Read') . " | " . anchor(site_url('pembayaran/update/$1'), 'Update') . " | " . anchor(site_url('pembayaran/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_pinjaman', $q);
        $this->db->or_like('angsuran', $q);
        $this->db->or_like('cicilan', $q);
        $this->db->or_like('tgl_jatuh_tempo', $q);
        $this->db->or_like('tgl_bayar', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('waktu_insert', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_pinjaman', $q);
        $this->db->or_like('angsuran', $q);
        $this->db->or_like('cicilan', $q);
        $this->db->or_like('tgl_jatuh_tempo', $q);
        $this->db->or_like('tgl_bayar', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('waktu_insert', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pembayaran_model.php */
/* Location: ./application/models/Pembayaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-26 04:35:23 */
/* http://harviacode.com */