<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pinjaman_model extends CI_Model
{

    public $table = 'pinjaman';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // Get data pinjaman
    public function get_data_pinjaman()
    {
        $this->db->order_by($this->id, $this->order);
        $temp = $this->db->get($this->table)->result_array();
        $result = $temp;
        $i = 0;
        foreach ($temp as $t) {
            $result[$i++]['id_anggota'] = $this->Anggota_model->get_by_id($t['id_anggota'])->nama;
        }
        return $result;
    }

    // Get data pinjaman by id
    public function get_data_pinjaman_by_id($id)
    {
        $this->db->where($this->id, $id);
        $temp = $this->db->get($this->table)->row();
        $result = $temp;
        $result->id_anggota = $this->Anggota_model->get_by_id($temp->id_anggota)->nama;
        $result->id_user = $this->User_model->get_by_id($temp->id_user)->username;
        return $result;
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,id_anggota,tgl_pinjam,jumlah,durasi,bunga,status,id_user,waktu_insert');
        $this->datatables->from('pinjaman');
        //add this line for join
        //$this->datatables->join('table2', 'pinjaman.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pinjaman/read/$1'), 'Read') . " | " . anchor(site_url('pinjaman/update/$1'), 'Update') . " | " . anchor(site_url('pinjaman/delete/$1'), 'Delete', 'onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_anggota', $q);
        $this->db->or_like('tgl_pinjam', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('durasi', $q);
        $this->db->or_like('bunga', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('waktu_insert', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_anggota', $q);
        $this->db->or_like('tgl_pinjam', $q);
        $this->db->or_like('jumlah', $q);
        $this->db->or_like('durasi', $q);
        $this->db->or_like('bunga', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('waktu_insert', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Pinjaman_model.php */
/* Location: ./application/models/Pinjaman_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-26 04:35:23 */
/* http://harviacode.com */