<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Simpanan_model extends CI_Model
{

    public $table = 'simpanan';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,id_anggota,id_jenis,tgl_simpan,jumlah,id_user,waktu_insert');
        $this->datatables->from('simpanan');
        //add this line for join
        //$this->datatables->join('table2', 'simpanan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('simpanan/read/$1'),'Read')." | ".anchor(site_url('simpanan/update/$1'),'Update')." | ".anchor(site_url('simpanan/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), '');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_anggota', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('tgl_simpan', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('waktu_insert', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('', $q);
	$this->db->or_like('id', $q);
	$this->db->or_like('id_anggota', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('tgl_simpan', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('waktu_insert', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Simpanan_model.php */
/* Location: ./application/models/Simpanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-02-26 11:37:12 */
/* http://harviacode.com */